services:
  postgres:
    ports: !override []
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  rabbitmq:
    ports: !override
      - "5672:5672"
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  bot-service:
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  worker-service:
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"
